name: lint

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  standardrb:
    name: StandardRB
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: "3.4"
          bundler-cache: true
      - name: Run StandardRB
        run: bundle exec rake standard
        env:
          STANDARDOPTS: --cache false

  cppcheck:
    name: Cppcheck
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Update apt index
        run: sudo apt-get update
      - name: Install cppcheck
        run: sudo apt-get install --yes --no-install-recommends cppcheck
      - name: Run cppcheck
        run: cppcheck --enable=style --error-exitcode=1 ext/envameleon/envameleon.c
